/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Frames;
import Core.Application;
import Core.FrameType;
import Core.FramesController;
import Database.InvalidUserCredentialsException;
import UI.UI_Variables;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Bubo & Yana
 */
public class LogInFrame extends javax.swing.JFrame {
    private Application _app;
    private FramesController _framesController;
    
    private String _username;
    private char[] _password;
    /**
     * Creates new form LogInFrame
     */
    public LogInFrame(Application application, FramesController framesController) {
        initComponents();
        _app = application;
        _framesController = framesController;
        
        //UI settings
        setSize(1920, 935);
        setBackground(UI_Variables.BACKGROUND_COLOR);
        
        setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        logInPanel = new javax.swing.JPanel();
        logInTitleLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        logInBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();
        haveAnAccountBtn = new javax.swing.JLabel();
        logInUserNameLabel = new javax.swing.JLabel();
        logInPasswordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 115, 115));

        backgroundPanel.setBackground(new java.awt.Color(255, 115, 115));

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setForeground(new java.awt.Color(0, 0, 0));
        logInPanel.setPreferredSize(new java.awt.Dimension(822, 890));
        logInPanel.setVerifyInputWhenFocusTarget(false);

        logInTitleLabel.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        logInTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        logInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInTitleLabel.setText("Welcome back!");
        logInTitleLabel.setPreferredSize(new java.awt.Dimension(565, 75));

        userNameTextField.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        userNameTextField.setPreferredSize(new java.awt.Dimension(524, 52));

        logInBtn.setBackground(new java.awt.Color(255, 115, 115));
        logInBtn.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(0, 0, 0));
        logInBtn.setText("Log In");
        logInBtn.setPreferredSize(new java.awt.Dimension(215, 85));
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        signUpBtn.setBackground(new java.awt.Color(255, 255, 255));
        signUpBtn.setFont(new java.awt.Font("Gadugi", 0, 32)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(0, 0, 0));
        signUpBtn.setText("Sign Up");
        signUpBtn.setPreferredSize(new java.awt.Dimension(204, 85));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        haveAnAccountBtn.setFont(new java.awt.Font("Gadugi", 0, 32)); // NOI18N
        haveAnAccountBtn.setForeground(new java.awt.Color(0, 0, 0));
        haveAnAccountBtn.setText("Don't have an account?");

        logInUserNameLabel.setFont(new java.awt.Font("Gadugi", 0, 28)); // NOI18N
        logInUserNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        logInUserNameLabel.setText("Username");

        logInPasswordLabel.setFont(new java.awt.Font("Gadugi", 0, 28)); // NOI18N
        logInPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        logInPasswordLabel.setText("Password");

        passwordField.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(524, 52));

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                        .addComponent(haveAnAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logInUserNameLabel)
                            .addComponent(logInPasswordLabel)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141))))
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(logInTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(logInTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(logInUserNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(logInPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haveAnAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Checks the if the user information is correct and logs in the user
    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // TODO add your handling code here:
        _username = userNameTextField.getText();
        _password = passwordField.getPassword();
        
        List<String> errors = validateInput();
        
        if(errors.size() == 0) {
            try {
                _app.logIn(_username, _password);
                
                _framesController.openFrame(FrameType.MAIN_FRAME);
                dispose();
            } catch (InvalidUserCredentialsException ex) {
                JOptionPane.showMessageDialog(this, "Username or password is incorrect!", "Error", 0);
            }
        }
        else {
            String errorMessage = "";
            
            for(var error : errors) {
                errorMessage = errorMessage.concat(error + '\n');
            }
            
            JOptionPane.showMessageDialog(this, errorMessage, "Error", 0);
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    //Opening SingUp frame
    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        _framesController.openFrame(FrameType.SIGN_UP_FRAME);
        dispose();
    }//GEN-LAST:event_signUpBtnActionPerformed

    //Errors
    private List<String> validateInput() {
        List<String> errors = new LinkedList<>();
        
        if(_username.isBlank()) {
            errors.add("Username field cannot be empty");
        }
        if(_password.length == 0) {
            errors.add("Password field cannot be empty");
        }
        
        return errors;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel haveAnAccountBtn;
    private javax.swing.JButton logInBtn;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JLabel logInPasswordLabel;
    private javax.swing.JLabel logInTitleLabel;
    private javax.swing.JLabel logInUserNameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
    }
